version: "3"

services:
  nginx:
    container_name: psh_nginx
    image: nginx:stable-alpine
    ports:
      - "80:80"
    volumes:
      - ./app:/var/www/html
      - ./.stack/nginx/conf.d/:/etc/nginx/conf.d/
    depends_on:
      - php
      - mysql
    networks:
      - app-network

  mysql:
    container_name: psh_mysql
    image: mysql:8.0.26
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - dbdata:/var/lib/mysql
      - ./.stack/mysql/schema:/docker-entrypoint-initdb.d
    #   - .docker/mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - app-network

  php:
    container_name: psh_statistics
    build: .
    image: php-pdo:fpm-alpine
    environment:
      MYSQL_HOST: psh_mysql
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ./app:/var/www/html
      - ./.stack/cron/game-cron:/var/www/game-cron
      - ./.stack/cron/init.sh:/data/init.sh
    command: /bin/sh /data/init.sh
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
volumes:
  dbdata:
    driver: local
